# Pre-commit hooks for local development
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=127']

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--extend-ignore=E203,W503']
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies: [types-python-dotenv]
        args: ['--ignore-missing-imports', '--config-file=mypy.ini']

